### ISSUE TITLE
Request for consent.

### ISSUE THREAD

**Issue by Weav3r** [Weav3r/Disposal#1]
@ket-c I humbly write to request for permission to use your hwcalc.ga api to build an unlocking app for publication. Of course, you'll be acknowledged.

**Comment by ket-c** [comment]
Sure, you can use.
Im happy to help.

**Comment by Weav3r** [comment]
@ket-c Thank you, I plan on linking to the webapp as well in the playstore (i.e if the app even gets approved) for those who might not be willing to install the app for one reason or the other. Example, storage constraints, unsupported os version, or simply can't be bothered downloading an app only to use it once. What do you think?

Final question, did you ever try to calculate an invalid IMEI?

**Comment by ket-c** [comment]
Ok. You can link it...

Answer to your second question. Yes it can detect invalid IMEI.

**Comment by ket-c** [comment]
I've updated the readme check it out
https://github.com/ket-c/huaweiv3calculator/blob/master/README.md

**Comment by Weav3r** [comment]
Okay thanks, sorry for the late reply though.
